version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_PASSWORD=postgres_password
    simple_blog_api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        depends_on:
            - postgres
        volumes:
                - /usr/app/node_modules
                - .:/usr/app
        environment:
        - POSTGRES_HOST=postgres
        - POSTGRES_PORT=5432
        - POSTGRES_USERNAME=postgres
        - POSTGRES_PASSWORD=postgres_password
        - POSTGRES_DB=postgres