	
# Base Image
FROM node:alpine
 
# Change workdir to '/app'
WORKDIR '/usr/app'
 
# Copy package.json into the
# container
COPY package.json .
 
# Install dependencies
RUN npm install
 
# Copy the rest of the files
# into the container
COPY . .
 
# Run this
CMD ["npm", "run", "start"]